[tool.poetry]
name = "digitalocean"
version = "0.0.1"
description = "Ansible DigitalOcean Collection"
authors = ["Mark Mercado <mmercado@digitalocean.com>", "Ari Kalfus <akalfus@digitalocean.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
ansible-core = "^2.15.12"
azure-core = "^1.30.2"
pydo = "^0.4.0"
boto3 = "^1.34.149"
jmespath = "^1.0.1"
setuptools = "71.1.0"

[tool.poetry.group.dev.dependencies]
ansible-lint = { version = "^6.22.2", markers = "platform_system != 'Windows'" }
black = "^24.4.2"
pre-commit = "^3.7.1"
pylint = "^3.2.3"
pytest = "^8.2.2"
antsibull-changelog = "^0.29.0"
antsibull-docs = "^2.11.0"
autopep8 = "^2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
