[tool.poetry]
name = "digitalocean"
version = "0.0.1"
description = "Ansible DigitalOcean Collection"
authors = ["Mark Mercado <mmercado@digitalocean.com>", "Ari Kalfus <akalfus@digitalocean.com>"]
license = "GPL-3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = "~3.9"
ansible-core = "^2.15.9"
azure-core = "^1.30.0"
pydo = "^0.2.0"
boto3 = "^1.34.39"
jmespath = "^1.0.1"
setuptools = "69.1.0"

[tool.poetry.group.dev.dependencies]
ansible-lint = { version = "^6.22.2", markers = "platform_system != 'Windows'" }
black = "^24.1.1"
pre-commit = "^3.6.0"
pylint = "^3.0.3"
pytest = "^8.0.0"
antsibull-changelog = "^0.23.0"
antsibull-docs = "^2.7.0"
autopep8 = "^2.0.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
