[tool.poetry]
name = "digitalocean"
version = "0.0.1"
description = "Ansible DigitalOcean Collection"
authors = ["Mark Mercado <mmercado@digitalocean.com>", "Ari Kalfus <akalfus@digitalocean.com>"]
license = "GPL-3.0"
readme = "README.md"
package-mode = false

[tool.poetry.dependencies]
python = "~3.11.11"
ansible-core = "^2.15.12"
azure-core = "1.31.0"
pydo = "^0.4.0"
boto3 = "^1.34.131"
jmespath = "^1.0.1"
setuptools = "70.1.0"
certifi = "2024.7.4"
aiohttp = "3.10.2"
cryptography = "43.0.1"

[tool.poetry.group.dev.dependencies]
ansible-lint = { version = "^25.11.0", markers = "platform_system != 'Windows'" }
black = "25.11.0"
pre-commit = "4.4.0"
pylint = "4.0.2"
pytest = "9.0.0"
pytest-xdist = "^3.5.0"
antsibull-changelog = "0.34.0"
antsibull-docs = "2.22.0"
autopep8 = "^2.3.1"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.pyright]
include = ["."]
executionEnvironments = [
  { root = ".", pythonVersion = "3.11", extraPaths = ["../../.."] }
]
extraPaths = ["../../.."]
